# Generated by Django 5.0.2 on 2024-02-10 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=15)),
                ('post', models.CharField(max_length=20)),
                ('Housename', models.CharField(max_length=20)),
                ('gmail', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=5)),
                ('photo', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Elderly_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=15)),
                ('post', models.CharField(max_length=20)),
                ('Housename', models.CharField(max_length=20)),
                ('gmail', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
                ('guardian_details', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=5)),
                ('photo', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('CAREGIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.caregiver')),
                ('ELDERLY_PERSON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.elderly_person')),
            ],
        ),
        migrations.AddField(
            model_name='elderly_person',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('FROMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log1', to='myapp.login')),
                ('TOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log2', to='myapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='caregiver',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.CreateModel(
            name='Medication_remainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_medicine', models.CharField(max_length=50)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
                ('ELDERLYPERSON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.elderly_person')),
            ],
        ),
    ]
